[package]
name = "mktool"
description = "General purpose utility to enhance pkgsrc/mk infrastructure"
version = "0.1.17"
authors = ["Jonathan Perkin <jonathan@perkin.org.uk>"]
readme = "README.md"
keywords = ["pkgsrc"]
license = "ISC"
repository = "https://github.com/jperkin/mktool"
homepage = "https://github.com/jperkin/mktool"
documentation = "https://docs.rs/mktool"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
indicatif = "0.17.8"
pkgsrc = "0.1.28"
reqwest = { version = "0.12.5", features = ["blocking"] }
thiserror = "1.0.63"
